[platformio]
default_envs = esp32-s3-wokwi-display

[env]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
framework = arduino
monitor_speed = 115200
build_flags =
    -D BOARD_HAS_PSRAM
    -D EPD_PWR_ACTIVE_LEVEL=HIGH
    -Os
    -I src/raylib/include
lib_deps =

[env:esp32-s3-devkitc-1]

[env:esp32-s3-weact-2in9-bw]
extends = env:esp32-s3-devkitc-1
build_flags =
    ${env:esp32-s3-devkitc-1.build_flags}
    -D EPD_ENABLE_PWR_PIN

[env:esp32-s3-wokwi-display]
extends = env:esp32-s3-devkitc-1
build_flags =
    ${env:esp32-s3-devkitc-1.build_flags}
    -D EPD_ENABLE_PWR_PIN
    -D EPD_WOKWI_SIM

[env:esp32-s3-wokwi-safe]
build_flags =
    ${env.build_flags}
    -D EPD_SIM_STUB
