#!/usr/bin/env python3
"""Generate embedded_sd_seed.h from sdcard/ directory content.
Run as pre-build script: extra_scripts = pre:tools/gen_sd_seed.py

After editing files in sdcard/, rebuild and the seed function picks up changes.
"""
import os
import sys


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)
    sdcard_dir = os.path.join(project_dir, 'sdcard')
    output_path = os.path.join(project_dir, 'src', 'generated', 'sd_seed.h')

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    files = []
    for root, dirs, filenames in os.walk(sdcard_dir):
        for fn in sorted(filenames):
            full = os.path.join(root, fn)
            rel = os.path.relpath(full, sdcard_dir)
            with open(full, 'r') as f:
                content = f.read()
            if ')"' in content:
                print(f'[gen_sd_seed] WARNING: {rel} contains )" — raw string unsafe, skipping')
                continue
            files.append((rel.replace('\\', '/'), content))

    lines = [
        '#pragma once',
        '// Generated by tools/gen_sd_seed.py — do not edit directly',
        '// Edit files in sdcard/ and rebuild to regenerate',
        '',
        '#include <cstddef>',
        '',
        'namespace esp32calc_alt {',
        'namespace seed_data {',
        '',
        'struct Entry {',
        '  const char* path;',
        '  const char* data;',
        '  size_t size;',
        '};',
        '',
    ]

    lines.append(f'constexpr size_t kFileCount = {len(files)};')
    lines.append('')

    for i, (relpath, content) in enumerate(files):
        vname = f'kFile{i}'
        lines.append(f'constexpr char {vname}[] = R"({content})";')

    lines.append('')
    lines.append('constexpr Entry kEntries[kFileCount] = {')
    for i, (relpath, content) in enumerate(files):
        comma = ',' if i < len(files) - 1 else ''
        lines.append(f'  {{"{relpath}", kFile{i}, sizeof(kFile{i}) - 1}}{comma}')
    lines.append('};')
    lines.append('')
    lines.append('}  // namespace seed_data')
    lines.append('}  // namespace esp32calc_alt')
    lines.append('')

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    print(f'[gen_sd_seed] {output_path} ({len(files)} files)')


if __name__ == '__main__':
    main()
